name: Main

on:
  push:
    tags:
    - "v*.*.*"
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: Install depend
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl3 pkg-config
    - uses: dtolnay/rust-toolchain@stable
    - name: Build binary
      run: |
        SQLX_OFFLINE=true cargo build -r
        mv target/release/jincms-core jincms-core.bin
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: jincms-core.bin
